/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brainfuck;

/**
 *
 * @author Junta Directiva 2
 */
public class BrainFuck {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here

        Naguebofuck n= new Naguebofuck ();
         //hola mundo
        //n.interpretar("MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO GUEBON COÑO MARICO MARICO MARICO MARICO MARICO MARICO MARICO COÑO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO COÑO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO COÑO MARICO MARICO MARICO COÑO MARICO VERGA VERGA VERGA VERGA VERGA NOJODA CABRON COÑO MARICO MARICO MAMAGUEVO COÑO COÑO MARICO MAMAGUEVO NOJODA NOJODA NOJODA MAMAGUEVO VERGA NOJODA NOJODA NOJODA MAMAGUEVO COÑO COÑO MARICO MARICO MAMAGUEVO VERGA MARICO MAMAGUEVO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MARICO MAMAGUEVO NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA MAMAGUEVO VERGA MARICO MARICO MARICO MAMAGUEVO COÑO MARICO MAMAGUEVO COÑO MARICO MAMAGUEVO COÑO MAMAGUEVO");
        //MADURO COÑOETUMADRE
        n.interpretar("MARICO MARICO GUEBON NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA COÑO MARICO VERGA CABRON COÑO MAMAGUEVO NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA MAMAGUEVO MARICO MARICO MARICO MAMAGUEVO COÑO NOJODA GUEBON NOJODA NOJODA NOJODA COÑO MARICO VERGA CABRON COÑO MAMAGUEVO NOJODA NOJODA NOJODA MAMAGUEVO NOJODA NOJODA NOJODA MAMAGUEVO MARICO GUEBON NOJODA NOJODA NOJODA NOJODA NOJODA COÑO MARICO MARICO VERGA CABRON COÑO MAMAGUEVO MARICO GUEBON NOJODA COÑO MARICO MARICO VERGA CABRON COÑO MARICO MAMAGUEVO GUEBON NOJODA COÑO MARICO MARICO MARICO MARICO MARICO VERGA CABRON COÑO MAMAGUEVO MARICO GUEBON MARICO MARICO MARICO MARICO COÑO NOJODA VERGA CABRON COÑO NOJODA NOJODA NOJODA MAMAGUEVO MARICO MARICO MARICO GUEBON NOJODA COÑO MARICO MARICO MARICO MARICO VERGA CABRON COÑO NOJODA MAMAGUEVO NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA MAMAGUEVO COÑO NOJODA GUEBON NOJODA NOJODA NOJODA COÑO MARICO VERGA CABRON COÑO NOJODA MAMAGUEVO MARICO MAMAGUEVO NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA MAMAGUEVO NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA NOJODA MAMAGUEVO MARICO MARICO MARICO MAMAGUEVO GUEBON NOJODA COÑO MARICO MARICO MARICO MARICO MARICO VERGA CABRON COÑO NOJODA NOJODA MAMAGUEVO NOJODA GUEBON NOJODA COÑO MARICO MARICO MARICO MARICO VERGA CABRON COÑO MARICO MAMAGUEVO");

    }
    
}
